version: '3.5'

services:
  rig:
    container_name: rig-host
    image: rig-host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3333:80"
    depends_on:
     - "postgres"
    networks:
      - rig-network

  postgres:
    container_name: rig-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - rig-network

networks:
  rig-network:
    driver: bridge